### ISSUE TITLE
关于模型命名空间

### ISSUE THREAD

**Issue by yangjiecao** [TinyLara/TinyLara#11]
Article.php范例的首部要加上命名空间，给出正确调用的例子：
namespace App\Model;
/**
* Article Model
*/
class Article extends \Illuminate\Database\Eloquent\Model {
  public $timestamps = false;
}
这样在控制器就可以开心的使用模型了
use App\Model\Article;

**Comment by johnlui** [comment]
啊。。这是因为最近在向命名空间迁移，还没有迁移完善导致的。。。
