### ISSUE TITLE
Support for namespaced controller

### ISSUE THREAD

**Issue by ghost** [TinyLara/TinyLara#4]
Hi,
Does TinyLara support namespaced controller?

**Comment by johnlui** [comment]
Yeah, TinyLara uses per-0.

From My iPhone

**Comment by liuyami** [comment]
autoload 能不能改成PSR-4？

**Comment by johnlui** [comment]
@liuyami you can do it yourself~

**Comment by johnlui** [comment]
@liuyami 已经支持啦
