### ISSUE TITLE
wrong way to call func

### ISSUE THREAD

**Issue by exgaliba** [TinyLara/TinyLara#6]
execute "composer update", and i get vendor/tinylara,
 i find some code in line 29 in ./framework/src/TinyLara/Validation/Validator.php like this "$reason = $this->$detail[0]($this->data[$attribute], $detail[1]);".
 when i run this framework i get some wrong message, 
i use  call_user_func_array()  instead  like "$reason = call_user_func_array([$this, $detail[0]], [$this->data[$attribute], $detail[1]]);"  to avoid wrong message.  my php version is 7.0.1

**Comment by johnlui** [comment]
I will make it support PHP 7 ASAP
